name: Docker CI/CD Pipeline

# Xác định sự kiện trigger cho pipeline, trong trường hợp này là push lên nhánh develop
on:
  push:
    branches:
      - develop

# Định nghĩa các jobs cần thực hiện
jobs:
  # Job 1: build và test
  # Job thực thi trên máy ảo ubuntu
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Sử dụng action "checkout" để sao copy code từ repository vào máy ảo Ubuntu
        uses: actions/checkout@v2

      - name:
          Login to Docker Hub
          # Sử dụng action "docker/login-action" để đăng nhập vào Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        # Build và test image được build ra bằng Docker
        run: |
          docker build -t next-basic .
          docker run next-basic npm run lint

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-basic:${{ github.sha }}

  deploy:
      needs: build_and_test
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2 
        - name: Build & Deploy
          env:
              PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              SERVER_HOST: ${{secrets.SERVER_HOST}}
              SSH_USER: ${{secrets.SSH_USER}}
        
          run: |
              echo "$PRIVATE_KEY" > private_key
              chmod 600 private_key
              ssh -v -o StrictHostKeyChecking=no -i private_key ${SSH_USER}@${SERVER_HOST}
                cd /home/ubuntu &&
                docker pull ${{ secrets.DOCKERHUB_USERNAME }}/next-basic:${{ github.sha }}
                docker stop next-container
                docker rm next-container
                docker run -d -p 3000:3000 --name next-container ${{ secrets.DOCKERHUB_USERNAME }}/next-basic:${{ github.sha }}
